/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;

import client.Chat.Chat;
import client.GUI.guiListeners.ChangeEmailListener;
import client.GUI.guiListeners.ChangePasswordListener;
import client.GUI.guiListeners.ChangeUsernameListener;
import client.ServerConnectionConstants.ChatMessagesConstants;
import client.ServerConnector.ServerConnector;

import java.awt.Image;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.SwingUtilities;

/**
 *
 * @author Adam
 */
public class Account extends javax.swing.JPanel {

	MainScreen mainScreenWindow;
	boolean light = false;
	boolean dark = true;

	private Chat chat;
	private ServerConnector serverConnector;

	public Account(MainScreen mainScreenParam, ServerConnector serverConnector, Chat chat) {
		mainScreenWindow = mainScreenParam;
		this.serverConnector = serverConnector;
		this.chat = chat;
		initComponents();
		try {
			Image defaultImage = ImageIO.read(new File("src/main/java/client/GUI/deaudlt.png"));
			Image scaledImage = defaultImage.getScaledInstance(300, 300, Image.SCALE_DEFAULT);
			avatar.setIcon(new ImageIcon(scaledImage));
		} catch (Exception e) {
			System.out.println(e);
		}
		email.setText(chat.getCurrentUserInfo().getString(ChatMessagesConstants.EMAIL.value()));
		nick.setText(chat.getCurrentUserInfo().getString(ChatMessagesConstants.USERNAME.value()));

		this.peopleButton.setIcon(new ImageIcon("src/main/java/client/GUI/PeoplePAP.png"));
		this.msuicButton.setIcon(new ImageIcon("src/main/java/client/GUI/MusicPAP.png"));
		this.accountButton.setIcon(new ImageIcon("src/main/java/client/GUI/AccountSettingsPAP.png"));
		mainScreenButton.setIcon(new ImageIcon("src/main/java/client/GUI/MainScreenPAP.png"));

	}

	public void Theme() {
		if (light == true & dark == false) {
			FlatLightLaf.setup();
			SwingUtilities.updateComponentTreeUI(this);
		} else if (light == false & dark == true) {
			FlatDarkLaf.setup();
			SwingUtilities.updateComponentTreeUI(this);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		logo = new javax.swing.JLabel();
		emailLabel = new javax.swing.JLabel();
		email = new javax.swing.JLabel();
		emailChangeLabel = new javax.swing.JLabel();
		emailChange = new javax.swing.JTextField();
		nickLabel = new javax.swing.JLabel();
		nick = new javax.swing.JLabel();
		nickChangeLabel = new javax.swing.JLabel();
		nickChange = new javax.swing.JTextField();
		emailChangeAccept = new javax.swing.JButton();
		nickChangeAccept = new javax.swing.JButton();
		passwordLabel = new javax.swing.JLabel();
		oldPasswordLabel = new javax.swing.JLabel();
		oldPassword = new javax.swing.JPasswordField();
		newPasswordLabel = new javax.swing.JLabel();
		newPassword = new javax.swing.JPasswordField();
		confirmPasswordLabel = new javax.swing.JLabel();
		confirmPassword = new javax.swing.JPasswordField();
		passwordAccept = new javax.swing.JButton();
		avatarLabel = new javax.swing.JLabel();
		peopleButton = new javax.swing.JButton();
		msuicButton = new javax.swing.JButton();
		accountButton = new javax.swing.JButton();
		mainScreenButton = new javax.swing.JButton();
		changeAvatarLabel = new javax.swing.JLabel();
		selectFileButton = new javax.swing.JButton();
		changeAvatarButton = new javax.swing.JButton();
		avatar = new javax.swing.JLabel();
		passwordChangeOutcome = new javax.swing.JLabel();

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		logo.setFont(new java.awt.Font("Segoe UI Semilight", 3, 48)); // NOI18N
		logo.setText("ConnectedByMusic");

		emailLabel.setText("E-mail:");

		email.setText("jLabel4");

		emailChangeLabel.setText("Change e-mail:");

		emailChange.setText("");

		nickLabel.setText("Nick:");

		nick.setText("jLabel4");

		nickChangeLabel.setText("Change nick:");

		nickChange.setText("");

		emailChangeAccept.setText("Accept");
		emailChangeAccept.addActionListener(new ChangeEmailListener(emailChange, serverConnector, chat, email));

		nickChangeAccept.setText("Accept");
		nickChangeAccept.addActionListener(new ChangeUsernameListener(nickChange, serverConnector, chat, nick));

		passwordLabel.setText("Password:");

		oldPasswordLabel.setText("Old password:");

		oldPassword.setText("");

		newPasswordLabel.setText("New password:");

		newPassword.setText("");

		confirmPasswordLabel.setText("Confirm password:");

		confirmPassword.setText("");

		passwordAccept.setText("Accept");
		passwordAccept.addActionListener(new ChangePasswordListener(oldPassword, newPassword, confirmPassword,
				serverConnector, chat, passwordChangeOutcome));

		avatarLabel.setText("Avatar:");

		peopleButton.setText("jButton1");
		peopleButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				peopleButtonActionPerformed(evt);
			}
		});

		msuicButton.setIcon(new javax.swing.ImageIcon("src/main/java/client/GUI/MusicPAP.png")); // NOI18N
		msuicButton.setText("jButton1");
		msuicButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				msuicButtonActionPerformed(evt);
			}
		});

		accountButton.setIcon(new javax.swing.ImageIcon("src/main/java/client/GUI/AccountSettingsPAP.png")); // NOI18N
		accountButton.setText("jButton1");
		accountButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				accountButtonActionPerformed(evt);
			}
		});

		mainScreenButton.setText("jButton1");
		mainScreenButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mainScreenButtonActionPerformed(evt);
			}
		});

		changeAvatarLabel.setText("Change avatar:");

		selectFileButton.setText("Select file");
		selectFileButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectFileButtonActionPerformed(evt);
			}
		});

		changeAvatarButton.setText("ChangeAvatar");
		changeAvatarButton.setToolTipText("");
		changeAvatarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				changeAvatarButtonActionPerformed(evt);
			}
		});

		avatar.setText("");

		passwordChangeOutcome.setText("Password Changed!");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(logo).addGap(0, 0, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(nick, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
										.addComponent(nickLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(email, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(emailChangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
														449, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(nickChangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
														448, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(nickChange, javax.swing.GroupLayout.DEFAULT_SIZE, 662,
														Short.MAX_VALUE)
												.addComponent(emailChange)))
								.addGroup(layout.createSequentialGroup()
										.addComponent(oldPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(oldPassword))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(newPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(confirmPasswordLabel,
														javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(newPassword).addComponent(confirmPassword)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(emailChangeAccept,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 144,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(nickChangeAccept,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 144,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createSequentialGroup()
												.addComponent(changeAvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
														181, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(passwordChangeOutcome)
														.addComponent(selectFileButton))))
										.addGap(0, 0, Short.MAX_VALUE)))
								.addGap(4, 4, 4))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(passwordAccept, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 144,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(changeAvatarButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 144,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 322,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(msuicButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 77,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(accountButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 77,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(mainScreenButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 77,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(peopleButton, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 77,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
												.createSequentialGroup().addGap(12, 12, 12).addComponent(
														peopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(layout.createSequentialGroup().addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(msuicButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 35,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(12, 12, 12)
																.addComponent(
																		accountButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 35,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(mainScreenButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 35,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(34, 34, 34).addComponent(passwordLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(oldPasswordLabel)
																		.addComponent(oldPassword,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(newPasswordLabel)
																		.addComponent(newPassword,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(confirmPasswordLabel)
																		.addComponent(
																				confirmPassword,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				passwordAccept,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				22,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(passwordChangeOutcome)))
														.addGroup(layout.createSequentialGroup().addGap(17, 17, 17)
																.addComponent(avatarLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		avatar, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
										.addGroup(layout.createSequentialGroup()
												.addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(emailLabel).addComponent(emailChangeLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(email).addComponent(emailChange,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(emailChangeAccept, javax.swing.GroupLayout.PREFERRED_SIZE,
														22, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(nickLabel).addComponent(nickChangeLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(nick).addComponent(nickChange,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(nickChangeAccept, javax.swing.GroupLayout.PREFERRED_SIZE,
														22, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(changeAvatarLabel).addComponent(selectFileButton))
										.addComponent(changeAvatarButton))
								.addContainerGap(348, Short.MAX_VALUE)));
	}// </editor-fold>

	private void peopleButtonActionPerformed(java.awt.event.ActionEvent evt) {
		mainScreenWindow.setContentPane(mainScreenWindow.people);
		mainScreenWindow.repaint();
		mainScreenWindow.revalidate();
	}

	private void msuicButtonActionPerformed(java.awt.event.ActionEvent evt) {
		mainScreenWindow.setContentPane(mainScreenWindow.music);
		mainScreenWindow.repaint();
		mainScreenWindow.revalidate();
	}

	private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void mainScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {
		mainScreenWindow.setContentPane(mainScreenWindow.mainScreen);
		mainScreenWindow.setVisible(true);
		mainScreenWindow.repaint();
		mainScreenWindow.revalidate();
	}

	private void emailChangeAcceptActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
		AvatarChooser avatarChooser = new AvatarChooser(new StringBuilder()); // TODO add changing avatar
		avatarChooser.setVisible(true);
	}

	private void passwordAcceptActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void changeAvatarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton accountButton;
	private javax.swing.JLabel avatar;
	private javax.swing.JLabel avatarLabel;
	private javax.swing.JButton changeAvatarButton;
	private javax.swing.JLabel changeAvatarLabel;
	private javax.swing.JPasswordField confirmPassword;
	private javax.swing.JLabel confirmPasswordLabel;
	private javax.swing.JLabel email;
	private javax.swing.JTextField emailChange;
	private javax.swing.JButton emailChangeAccept;
	private javax.swing.JLabel emailChangeLabel;
	private javax.swing.JLabel emailLabel;
	private javax.swing.JEditorPane jEditorPane1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JLabel logo;
	private javax.swing.JButton mainScreenButton;
	private javax.swing.JButton msuicButton;
	private javax.swing.JPasswordField newPassword;
	private javax.swing.JLabel newPasswordLabel;
	private javax.swing.JLabel nick;
	private javax.swing.JTextField nickChange;
	private javax.swing.JButton nickChangeAccept;
	private javax.swing.JLabel nickChangeLabel;
	private javax.swing.JLabel nickLabel;
	private javax.swing.JPasswordField oldPassword;
	private javax.swing.JLabel oldPasswordLabel;
	private javax.swing.JButton passwordAccept;
	private javax.swing.JLabel passwordChangeOutcome;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JButton peopleButton;
	private javax.swing.JButton selectFileButton;
	// End of variables declaration
}
