/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.GUI;

import java.nio.file.Files;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Adam
 */
public class AvatarChooser extends javax.swing.JFrame {

    /**
     * Creates new form AvatarChooser
     */
    StringBuilder outputPath;

    public AvatarChooser(StringBuilder outputPath) {
        this.outputPath = outputPath;
        initComponents();
        avatarChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        avatarChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avatarChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(avatarChooser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(avatarChooser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void avatarChooserActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println(1234);
        int returnVal = this.avatarChooser.showOpenDialog(this);
        String path = avatarChooser.getSelectedFile().getAbsolutePath();
        System.out.println(path);
        System.out.println(234);
        if (returnVal == this.avatarChooser.APPROVE_OPTION
                && (path.substring(path.lastIndexOf("."), path.length()).equals(".png")
                        || path.substring(path.lastIndexOf("."), path.length()).equals(".jpg"))) {
            System.out.println(path);
            outputPath.delete(0, outputPath.length());
            outputPath.append(path);
            this.dispose();
        }
        if (returnVal == this.avatarChooser.CANCEL_OPTION) {
            this.dispose();
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JFileChooser avatarChooser;
    // End of variables declaration
}
