/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.GUI;

import java.util.ArrayList;
import java.util.Hashtable;

import org.json.JSONObject;

import client.Chat.Chat;
import client.GUI.listeners.ChatListener;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Adam
 */
public class Conversations extends javax.swing.JFrame {
    private Chat chat;
    private Hashtable<String, Integer> conversation_name_to_id;
    public ArrayList<JSONObject> current_messages;

    /**
     * Creates new form Conversations
     */
    public void change_messages(String conversation_name) {
        current_messages = chat.switch_conversations(conversation_name_to_id.get(conversation_name));
        set_conversation_text(current_messages);

    }

    private void set_conversation_text(ArrayList<JSONObject> messages) {
        jPanel1.removeAll();
        Hashtable<Integer, JSONObject> users_in_conv = chat.get_users_in_current_conversation();
        for (JSONObject message : messages) {
            System.out.println(message);
            // to_return +=
            // users_in_conv.get(message.getInt("sender_id")).getString("username") + "\n";
            // to_return += message.getString("text") + "\n\n";
            // // to_return += message.getString("send_date") + "\n";
            // String username =
            // users_in_conv.get(message.getInt("sender_id")).getString("username");
            LeftChatPanel leftChatPanel = new LeftChatPanel();
            if (message.getInt("sender_id") == chat.user_id()) {
                leftChatPanel.jTextArea1.setBackground(new java.awt.Color(0, 137, 255));
            }
            leftChatPanel.jTextArea1.setText(message.getString("text"));
            this.jPanel1.add(leftChatPanel.jTextArea1, "wrap");
            this.jPanel1.repaint();
            this.jPanel1.revalidate();
            this.jTextArea2.setText("");
        }
    }

    public Conversations(Chat chat) {
        this.chat = chat;
        conversation_name_to_id = this.chat.get_conversations_names_to_ids();
        current_messages = chat.get_current_messages();
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.jTextArea1.setEditable(false);
        this.jTextArea1.setText("");
        this.jTextArea1.setLineWrap(true);
        this.jTextArea2.setColumns(45);
        this.jTextArea2.setLineWrap(true);
        this.jTextArea1.setWrapStyleWord(true);
        this.jTextArea2.setWrapStyleWord(true);
        this.jPanel1.setLayout(new MigLayout("fillx"));
    }

    private void send_message() {
        String message = this.jTextArea2.getText().trim();
        if (!message.equals("")) {
            add_message_to_chat(chat.send_message(message));
        }
        System.out.println(current_messages);
    }

    private void add_message_to_chat(JSONObject message) {
        current_messages.add(message);
        set_conversation_text(current_messages);
    }

    /**
     * Creates new form Conversations
     */
    public Conversations() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.jTextArea1.setEditable(false);
        this.jTextArea1.setText("");
        this.jTextArea1.setLineWrap(true);
        this.jTextArea2.setColumns(45);
        this.jTextArea2.setLineWrap(true);
        this.jTextArea1.setWrapStyleWord(true);
        this.jTextArea2.setWrapStyleWord(true);
        this.jPanel1.setLayout(new MigLayout("fillx"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Start talking:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Chats:");

        String[] conv_names = new String[conversation_name_to_id.keySet().size()];
        int i = 0;
        for (String name : conversation_name_to_id.keySet()) {
            conv_names[i++] = name;
        }

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = conv_names;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });

        jList1.addListSelectionListener(new ChatListener(this));
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("User or group name");

        jButton2.setText("Go to");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 377, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 287, Short.MAX_VALUE));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 116,
                                                Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 275,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton1,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jScrollPane3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 379,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap()))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        send_message();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedFriend = new String();
        selectedFriend = jList1.getSelectedValue().toString();
        if (selectedFriend.equals("a")) {
            jTextArea1.setText("AAA");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversations.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversations.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversations.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversations.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration
}
