/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;

import client.Chat.Chat;
import client.GUI.guiListeners.SendMessageListener;
import client.GUI.guiListeners.SwitchConversationListener;

import java.awt.Color;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

public class People extends javax.swing.JPanel {

        boolean light = false;
        boolean dark = true;
        MainScreen mainScreenWindow;

        private Chat chat;

        public People(MainScreen mainScreenParam, Chat chat) {
                this.chat = chat;
                mainScreenWindow = mainScreenParam;
                initComponents();
                this.membersList.setEditable(true);
                this.textArea.setText("sssssss");
                this.membersList.setLineWrap(true);
                this.textArea.setColumns(45);
                this.textArea.setLineWrap(true);
                this.membersList.setWrapStyleWord(true);
                this.textArea.setWrapStyleWord(true);
                this.chatPanel.setLayout(new MigLayout("fillx"));
        }

        public void Theme() {
                if (light == true & dark == false) {
                        FlatLightLaf.setup();
                        SwingUtilities.updateComponentTreeUI(this);
                } else if (light == false & dark == true) {
                        FlatDarkLaf.setup();
                        SwingUtilities.updateComponentTreeUI(this);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                logo = new javax.swing.JLabel();
                createGroupLabel = new javax.swing.JLabel();
                groupNameLabel = new javax.swing.JLabel();
                groupName = new javax.swing.JTextField();
                groupCodeLabel = new javax.swing.JLabel();
                membersLabel = new javax.swing.JLabel();
                membersContainer = new javax.swing.JScrollPane();
                membersList = new javax.swing.JTextArea();
                joinToGroupLabel = new javax.swing.JLabel();
                groupCodeLabel2 = new javax.swing.JLabel();
                groupCode2 = new javax.swing.JTextField();
                joinButton = new javax.swing.JButton();
                chatsLabel = new javax.swing.JLabel();
                userOrGroupNameLabel = new javax.swing.JLabel();
                chatsContainer = new javax.swing.JScrollPane();
                chatsList = new javax.swing.JList<>();
                textContainer = new javax.swing.JScrollPane();
                textArea = new javax.swing.JTextArea();
                sendButton = new javax.swing.JButton();
                addPersonToGroupLabel = new javax.swing.JLabel();
                createButton = new javax.swing.JButton();
                groupCode = new javax.swing.JTextField();
                peopleButton = new javax.swing.JButton();
                musicButton = new javax.swing.JButton();
                accountButton = new javax.swing.JButton();
                mainScreenButton = new javax.swing.JButton();
                chatContainer = new javax.swing.JScrollPane();
                chatPanel = new javax.swing.JPanel();
                photoButton = new javax.swing.JButton();
                peopleContainer = new javax.swing.JScrollPane();
                peopleList = new javax.swing.JList<>();
                addButton = new javax.swing.JButton();
                removePersonFromGroupLabel = new javax.swing.JLabel();
                peopleListRemove = new javax.swing.JList<>();
                removeButton = new javax.swing.JButton();
                changeChatNameLabel = new javax.swing.JLabel();
                changeChatName = new javax.swing.JTextField();
                changeButton = new javax.swing.JButton();
                membersInConvLabel = new javax.swing.JLabel();
                membersInConContainer = new javax.swing.JScrollPane();
                membersInConvList = new javax.swing.JList<>();

                setPreferredSize(new java.awt.Dimension(1280, 712));

                logo.setFont(new java.awt.Font("Segoe UI Semilight", 3, 48)); // NOI18N
                logo.setText("ConnectedByMusic");

                createGroupLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
                createGroupLabel.setText("Create group:");

                groupNameLabel.setText("Group name:");

                groupName.setText("jTextField1");

                groupCodeLabel.setText("Group code:");

                membersLabel.setText("Members (example: friend1,friend2,friend3...):");

                membersList.setColumns(20);
                membersList.setRows(5);
                membersContainer.setViewportView(membersList);

                joinToGroupLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
                joinToGroupLabel.setText("Join to group:");

                groupCodeLabel2.setText("Group Code:");

                groupCode2.setText("jTextField1");

                joinButton.setText("Join");
                joinButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                joinButtonActionPerformed(evt);
                        }
                });

                chatsLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
                chatsLabel.setText("Chats:");

                userOrGroupNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
                userOrGroupNameLabel.setText("User or group name:");

                var convNamesSet = chat.getConversationsNamesToIds().keySet();

                String[] convNames = new String[convNamesSet.size()];
                int i = 0;
                for (String name : convNamesSet) {
                        convNames[i++] = name;
                }

                chatsList.setModel(new javax.swing.AbstractListModel<String>() {

                        public int getSize() {
                                return convNames.length;
                        }

                        public String getElementAt(int i) {
                                return convNames[i];
                        }
                });

                chatsList.addListSelectionListener(new SwitchConversationListener(chat, chatPanel));

                chatsContainer.setViewportView(chatsList);

                textArea.setColumns(20);
                textArea.setRows(5);
                textContainer.setViewportView(textArea);

                sendButton.setText("Send");
                sendButton.addActionListener(new SendMessageListener(chat, textArea, chatPanel));

                addPersonToGroupLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                addPersonToGroupLabel.setText("Add person to current group:");

                createButton.setText("Create");
                createButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createButtonActionPerformed(evt);
                        }
                });

                groupCode.setText("jTextField1");

                peopleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adam\\Desktop\\PeoplePAP.png")); // NOI18N
                peopleButton.setText("jButton1");
                peopleButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                peopleButtonActionPerformed(evt);
                        }
                });

                musicButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adam\\Desktop\\MusicPAP.png")); // NOI18N
                musicButton.setText("jButton1");
                musicButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                musicButtonActionPerformed(evt);
                        }
                });

                accountButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adam\\Desktop\\AccountSettingsPAP.png")); // NOI18N
                accountButton.setText("jButton1");
                accountButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                accountButtonActionPerformed(evt);
                        }
                });

                mainScreenButton.setText("jButton1");
                mainScreenButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mainScreenButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
                chatPanel.setLayout(chatPanelLayout);
                chatPanelLayout.setHorizontalGroup(
                                chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 644, Short.MAX_VALUE));
                chatPanelLayout.setVerticalGroup(
                                chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 739, Short.MAX_VALUE));

                chatContainer.setViewportView(chatPanel);

                photoButton.setText("Add photo");
                photoButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                photoButtonActionPerformed(evt);
                        }
                });

                peopleList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                peopleContainer.setViewportView(peopleList);

                addButton.setText("Add");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });

                removePersonFromGroupLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                removePersonFromGroupLabel.setText("Remove person from current group:");

                peopleListRemove.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });

                removeButton.setText("Remove");
                removeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                removeButtonActionPerformed(evt);
                        }
                });

                changeChatNameLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                changeChatNameLabel.setText("Change current chat name:");

                changeChatName.setText("jTextField1");

                changeButton.setText("Chnage");
                changeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                changeButtonActionPerformed(evt);
                        }
                });

                membersInConvLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
                membersInConvLabel.setText("Members:");

                membersInConvList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "a", "b", "c" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                membersInConContainer.setViewportView(membersInConvList);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(logo,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(groupCodeLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(groupCode2)
                                                                                                                                .addGap(4, 4, 4))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(groupCodeLabel,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(groupNameLabel,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(groupCode)
                                                                                                                                                .addComponent(groupName))
                                                                                                                                .addGap(2, 2, 2))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(membersContainer,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(createButton,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGap(4, 4, 4))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(addPersonToGroupLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGap(189, 189,
                                                                                                                                                189))
                                                                                                                .addComponent(joinToGroupLabel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                397,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(membersLabel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                399,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(joinButton,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGap(4, 4, 4)))
                                                                                                .addGap(6, 6, 6))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(createGroupLabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(removePersonFromGroupLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addGap(63, 63, 63)
                                                                                                                                                                .addComponent(addButton,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addComponent(peopleListRemove,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(peopleContainer)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(changeChatNameLabel,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addGap(129, 129,
                                                                                                                                                                                                                129))
                                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(changeChatName,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                315,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(changeButton,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(removeButton,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE))))
                                                                                                                                .addGap(7, 7, 7)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(chatsLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                125, Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(membersInConvLabel)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(membersInConContainer))
                                                                                                                                .addComponent(chatsContainer))
                                                                                                                .addGap(6, 6, 6)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(userOrGroupNameLabel,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(117, 117, 117))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(chatContainer,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                653,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(textContainer)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(photoButton)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(sendButton,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                62,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(peopleButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                77,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(musicButton,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                77,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(accountButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                77,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(mainScreenButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                77,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(logo)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(addPersonToGroupLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                .addContainerGap()
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                .addComponent(chatsLabel)
                                                                                                                                                                .addComponent(userOrGroupNameLabel))))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(chatContainer,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                0,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGap(29, 29, 29))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(peopleContainer,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                58,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(addButton,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addGap(18, 18, 18))
                                                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                                                .addGap(16, 16, 16)
                                                                                                                                                                                                                .addComponent(removePersonFromGroupLabel,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                                                                                                                .addComponent(peopleListRemove,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                40,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(removeButton,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                24,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addGap(63, 63, 63))
                                                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                                                .addGap(21, 21, 21)
                                                                                                                                                                                                                .addComponent(changeChatNameLabel,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                                                                                .addComponent(changeChatName,
                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                .addComponent(changeButton))
                                                                                                                                                                                                                .addGap(17, 17, 17)))
                                                                                                                                                                .addComponent(createGroupLabel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                                .addComponent(groupNameLabel)
                                                                                                                                                                                .addComponent(groupName,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(groupCodeLabel)
                                                                                                                                                                                .addComponent(groupCode,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                .addComponent(chatsContainer))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(membersLabel)
                                                                                                                                                .addComponent(membersInConvLabel))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(membersContainer,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                98,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(createButton)
                                                                                                                                                                .addGap(61, 61, 61)
                                                                                                                                                                .addComponent(joinToGroupLabel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                                .addComponent(groupCodeLabel2)
                                                                                                                                                                                .addComponent(groupCode2,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGap(32, 32, 32))
                                                                                                                                                .addComponent(membersInConContainer)))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(12, 12, 12)
                                                                                                .addComponent(peopleButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(11, 11, 11)
                                                                                                .addComponent(musicButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(accountButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(mainScreenButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(joinButton,
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(sendButton)
                                                                                                                                                .addComponent(photoButton)))
                                                                                                                .addComponent(textContainer,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                23,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap()));
        }// </editor-fold>

        private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void peopleButtonActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void musicButtonActionPerformed(java.awt.event.ActionEvent evt) {
                mainScreenWindow.setContentPane(mainScreenWindow.music);
                mainScreenWindow.repaint();
                mainScreenWindow.revalidate();
        }

        private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {
                mainScreenWindow.setContentPane(mainScreenWindow.account);
                mainScreenWindow.repaint();
                mainScreenWindow.revalidate();
        }

        private void mainScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {
                mainScreenWindow.setContentPane(mainScreenWindow.mainScreen);
                mainScreenWindow.setVisible(true);
                mainScreenWindow.repaint();
                mainScreenWindow.revalidate();
        }

        private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {
                AvatarChooser photoChooser = new AvatarChooser();
                photoChooser.setVisible(true);
        }

        private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        // Variables declaration - do not modify
        private javax.swing.JButton accountButton;
        private javax.swing.JButton addButton;
        private javax.swing.JLabel addPersonToGroupLabel;
        private javax.swing.JButton changeButton;
        private javax.swing.JTextField changeChatName;
        private javax.swing.JLabel changeChatNameLabel;
        private javax.swing.JScrollPane chatContainer;
        private javax.swing.JPanel chatPanel;
        private javax.swing.JScrollPane chatsContainer;
        private javax.swing.JLabel chatsLabel;
        private javax.swing.JList<String> chatsList;
        private javax.swing.JButton createButton;
        private javax.swing.JLabel createGroupLabel;
        private javax.swing.JTextField groupCode;
        private javax.swing.JTextField groupCode2;
        private javax.swing.JLabel groupCodeLabel;
        private javax.swing.JLabel groupCodeLabel2;
        private javax.swing.JTextField groupName;
        private javax.swing.JLabel groupNameLabel;
        private javax.swing.JButton joinButton;
        private javax.swing.JLabel joinToGroupLabel;
        private javax.swing.JLabel logo;
        private javax.swing.JButton mainScreenButton;
        private javax.swing.JScrollPane membersContainer;
        private javax.swing.JScrollPane membersInConContainer;
        private javax.swing.JLabel membersInConvLabel;
        private javax.swing.JList<String> membersInConvList;
        private javax.swing.JLabel membersLabel;
        private javax.swing.JTextArea membersList;
        private javax.swing.JButton musicButton;
        private javax.swing.JButton peopleButton;
        private javax.swing.JScrollPane peopleContainer;
        private javax.swing.JList<String> peopleList;
        private javax.swing.JList<String> peopleListRemove;
        private javax.swing.JButton photoButton;
        private javax.swing.JButton removeButton;
        private javax.swing.JLabel removePersonFromGroupLabel;
        private javax.swing.JButton sendButton;
        private javax.swing.JTextArea textArea;
        private javax.swing.JScrollPane textContainer;
        private javax.swing.JLabel userOrGroupNameLabel;
        // End of variables declaration
}
